//! EffectCraft desktop app.
//!
//! Usage: `effectcraft [--control <port>] [--demo|--empty|--home] [project.ecproj | media files…]`
//!
//! Without a project the app starts with an empty Untitled Project, as After Effects does;
//! `--demo` opens the demo project instead (also Help ▸ Open Demo Project).
//!
//! `--control <port>` (or `EFFECTCRAFT_CONTROL_PORT`) starts a localhost JSON-lines control server;
//! see `effectcraft_ui_egui::control` for the methods.
#![cfg_attr(all(target_os = "windows", not(debug_assertions)), windows_subsystem = "windows")]
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::unimplemented, clippy::todo, clippy::unreachable)]

// Built everywhere so its tests run on every platform; only Linux AppImages use it.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
mod appimage;
mod audio_out;
mod control_server;
mod launch_guard;
#[cfg(target_os = "macos")]
mod native_menu;

use effectcraft_ui_egui::EffectcraftApp;
use serde_json::json;

/// The app icon for the window, taskbar and Dock (assets/app-icon, regenerated by
/// `packaging/icons.sh`). macOS gets the padded variant so it sits on Apple's icon grid in the Dock.
/// The 256 px app icon (Windows, Linux; the AppImage's desktop integration installs it too).
#[cfg(not(target_os = "macos"))]
const ICON_PNG: &[u8] = include_bytes!("../../../assets/app-icon/hicolor/256x256/apps/ai.storyteller.effectcraft.png");

fn app_icon() -> egui::IconData {
    #[cfg(target_os = "macos")]
    let png: &[u8] = include_bytes!("../../../assets/app-icon/effectcraft-macos-512.png");
    #[cfg(not(target_os = "macos"))]
    let png: &[u8] = ICON_PNG;
    eframe::icon_data::from_png_bytes(png).unwrap_or_default()
}

/// The command line.
#[derive(Debug, Default, PartialEq)]
struct Args {
    control_port: Option<u16>,
    files: Vec<String>,
    /// Open the demo project when no project is given (`--demo`).
    demo: bool,
    /// Show or skip the Home screen (`--home`), else the Startup preference decides.
    home: Option<bool>,
}

/// Parse the arguments after the program name; `None` for `--version`. `env_port` is
/// `EFFECTCRAFT_CONTROL_PORT`.
fn parse_args(args: impl IntoIterator<Item = String>, env_port: Option<String>) -> Option<Args> {
    let mut out = Args { control_port: env_port.and_then(|p| p.parse().ok()), ..Default::default() };
    let mut args = args.into_iter();
    while let Some(a) = args.next() {
        match a.as_str() {
            "--control" => out.control_port = args.next().and_then(|p| p.parse().ok()),
            "--demo" => out.demo = true,
            "--empty" => out.demo = false,
            "--home" => out.home = Some(true),
            "--version" => return None,
            _ => out.files.push(a),
        }
    }
    Some(out)
}

fn main() -> eframe::Result {
    // Help ▸ Enable Logging writes through this logger; warnings feed the compatibility report.
    effectcraft_engine::logging::install();
    effectcraft_engine::logging::install_panic_hook();
    let Some(Args { control_port, files, demo, home }) = parse_args(std::env::args().skip(1), std::env::var("EFFECTCRAFT_CONTROL_PORT").ok()) else {
        println!("effectcraft {}", env!("CARGO_PKG_VERSION"));
        return Ok(());
    };
    // The font menus list the installed fonts: read their names while the window opens.
    effectcraft_engine::text::fonts::scan_system_in_background();
    // Wayland shows the window's icon from its desktop entry: an AppImage brings its own.
    #[cfg(target_os = "linux")]
    appimage::integrate_from_env(ICON_PNG);
    // Settings ▸ Startup & Repair ▸ Window Graphics, switched to OpenGL when the last launch's
    // window never drew (a crashing graphics driver, #243).
    let mut launch = launch_guard::Launch::begin(effectcraft_host::config_dir().as_deref(), std::env::var_os("WGPU_BACKEND").is_some());
    let on_gl = launch.backends == Some(eframe::wgpu::Backends::GL);
    let notice = launch.notice.take();
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_title("EffectCraft")
            .with_inner_size([1680.0, 1020.0])
            .with_min_inner_size([960.0, 600.0])
            .with_drag_and_drop(true)
            // Started for an agent (`--control`): open without taking the user's keyboard focus.
            .with_active(control_port.is_none())
            .with_icon(app_icon())
            // Wayland matches the window to `ai.storyteller.effectcraft.desktop` by this ID.
            .with_app_id(appimage::APP_ID),
        event_loop_builder: agent_event_loop(control_port.is_some()),
        wgpu_options: wgpu_options(launch.backends),
        ..Default::default()
    };
    // Start-up milestones: with `RUST_LOG=info` they go to stderr, so a window that never
    // appears shows how far start-up got (#234).
    log::info!("effectcraft {}: opening the window", env!("CARGO_PKG_VERSION"));
    #[cfg(all(unix, not(target_os = "macos")))]
    let mut options = options;
    // winit has no file drag-and-drop on Wayland (only on X11), so dropping files from the file
    // manager showed a "no" cursor. Run through XWayland when it's there; EFFECTCRAFT_WAYLAND=1
    // keeps the native Wayland backend.
    #[cfg(all(unix, not(target_os = "macos")))]
    if std::env::var_os("DISPLAY").is_some() && std::env::var_os("EFFECTCRAFT_WAYLAND").is_none() {
        options.event_loop_builder = Some(Box::new(|b| {
            use winit::platform::x11::EventLoopBuilderExtX11;
            b.with_x11();
        }));
    }
    let result = eframe::run_native(
        "EffectCraft",
        options,
        Box::new(move |cc| {
            match &cc.wgpu_render_state {
                Some(rs) => log::info!("graphics: {:?}", rs.adapter.get_info()),
                None => log::info!("graphics: no wgpu device"),
            }
            // This executable owns the shared device's handlers. Install them before
            // EffectCraft's compositor pipelines are built, without changing handlers from
            // inside Gpu::new. eframe has already constructed its presentation renderer here.
            let gpu_failures = effectcraft_ui_egui::gpu_failure::GpuFailureBridge::new(&cc.egui_ctx);
            if let Some(rs) = &cc.wgpu_render_state {
                let errors = gpu_failures.clone();
                rs.device.on_uncaptured_error(std::sync::Arc::new(move |error| {
                    let message = format!("uncaptured GPU error: {error}");
                    if errors.report(&message, false) {
                        log::error!("{message}");
                    }
                }));
                let lost = gpu_failures.clone();
                rs.device.set_device_lost_callback(move |reason, message| {
                    lost.report(&format!("GPU device lost ({reason:?}): {message}"), true);
                });
            }
            let mut session = effectcraft_host::session();
            // Lazy open and non-blocking auto-save: footage is checked and auto-saves are
            // written on background threads (M13.14).
            session.check_footage_on_open = true;
            session.autosave.background = true;
            // Settings, shortcut presets and the crash-recovery sentinel live in the platform
            // config directory. Agent-driven runs (`--control`) skip crash recovery.
            if let Some(dir) = effectcraft_host::config_dir() {
                // WebAssembly effect plug-ins in <config>/Plug-ins load before the menus are built.
                let plugins = dir.join("Plug-ins");
                if plugins.is_dir() {
                    let _ = session.execute("effect.plugins.load", json!({"folder": plugins.to_string_lossy()}));
                }
                session.config = Some(std::sync::Arc::new(effectcraft_engine::config::DirConfig::new(dir)));
            }
            session.load_settings();
            let recovery = if control_port.is_none() { session.begin_recovery() } else { None };
            let project = files.iter().find(|f| f.ends_with(".ecproj")).cloned();
            if let Some(p) = project {
                if let Err(e) = session.execute("file.open", json!({"path": p})) {
                    eprintln!("effectcraft: {e}");
                }
            } else if demo {
                let _ = session.execute("file.openDemoProject", json!({}));
            }
            let media: Vec<String> = files.iter().filter(|f| !f.ends_with(".ecproj")).cloned().collect();
            if !media.is_empty()
                && let Err(e) = session.execute("file.import", json!({"paths": media}))
            {
                eprintln!("effectcraft: {e}");
            }
            let show_home = home.unwrap_or(session.prefs.startup.show_home_on_launch && files.is_empty() && control_port.is_none());
            // The ScriptUI panels open when the app last quit open again (a failing one is
            // reported in a toast and forgotten).
            let _ = session.execute("window.restoreScriptPanels", json!({}));
            let mut app = EffectcraftApp::new(session);
            app.set_gpu_failure_bridge(gpu_failures);
            app.ui.start_screen = show_home;
            if let Some(n) = notice {
                app.ui.status = n;
            }
            if let Some(r) = recovery {
                app.offer_recovery(r);
            }
            app.hooks.pick_files = Some(Box::new(|exts: &[&str]| {
                rfd::FileDialog::new().add_filter("Media", exts).pick_files().unwrap_or_default().into_iter().map(|p| p.to_string_lossy().to_string()).collect()
            }));
            app.hooks.pick_save = Some(Box::new(|name: &str| {
                rfd::FileDialog::new().add_filter("EffectCraft Project", &["ecproj"]).set_file_name(name).save_file().map(|p| p.to_string_lossy().to_string())
            }));
            app.hooks.pick_open_project = Some(Box::new(|| {
                rfd::FileDialog::new().add_filter("EffectCraft Project", &["ecproj", "ecprojx"]).pick_file().map(|p| p.to_string_lossy().to_string())
            }));
            app.hooks.audio_device = Some(Box::new(audio_out::open));
            app.hooks.audio_devices = Some(Box::new(audio_out::devices));
            app.hooks.pick_folder = Some(Box::new(|| rfd::FileDialog::new().pick_folder().map(|p| p.to_string_lossy().to_string())));
            app.hooks.pick_save_file = Some(Box::new(|name: &str, ext: &str| {
                // A default with a folder that exists opens the dialog there.
                let path = std::path::Path::new(name);
                // (No filter for a name without an extension, such as a folder to create.)
                let mut d = if ext.is_empty() { rfd::FileDialog::new() } else { rfd::FileDialog::new().add_filter(ext, &[ext]) };
                if let Some(dir) = path.parent().filter(|d| d.is_dir()) {
                    d = d.set_directory(dir);
                }
                let file = path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default();
                d.set_file_name(file).save_file().map(|p| p.to_string_lossy().to_string())
            }));
            #[cfg(target_os = "macos")]
            {
                app.hooks.app_action = Some(Box::new(native_menu::app_action));
                app.hooks.clipboard_text = Some(Box::new(native_menu::clipboard_text));
            }
            if let Some(port) = control_port {
                disable_app_nap();
                let rx = control_server::start(port, cc.egui_ctx.clone());
                app = app.with_control(rx);
            }
            log::info!("app created; the window shows after its first frame");
            Ok(Box::new(Desktop {
                #[cfg(target_os = "macos")]
                menu: native_menu::NativeBar::new(&cc.egui_ctx),
                app,
                launch,
                drawn: false,
            }))
        }),
    );
    match &result {
        Ok(()) => log::info!("the window closed"),
        Err(e) => {
            if on_gl {
                launch_guard::opengl_failed(effectcraft_host::config_dir().as_deref());
            }
            startup_failed(e, !on_gl && cfg!(not(target_os = "macos")));
        }
    }
    result
}

/// The window's wgpu device asks for the adapter's own limits (textures up to 16384 px)
/// instead of eframe's fixed set: an older GPU that can't meet those (Intel HD Graphics 5500,
/// #198) still opens the app, and the compositor then checks what it needs and falls back to
/// the CPU when the device can't run it. `backends`: Window Graphics' choice, when it makes one.
fn wgpu_options(backends: Option<eframe::wgpu::Backends>) -> eframe::WgpuConfiguration {
    use eframe::egui_wgpu::WgpuSetup;
    let mut config = eframe::WgpuConfiguration::default();
    if let WgpuSetup::CreateNew(setup) = &mut config.wgpu_setup {
        if let Some(b) = backends {
            setup.instance_descriptor.backends = b;
        }
        setup.device_descriptor = std::sync::Arc::new(|adapter| eframe::wgpu::DeviceDescriptor {
            label: Some("EffectCraft device"),
            required_limits: device_limits(adapter.limits()),
            ..Default::default()
        });
    }
    config
}

/// The limits to request from an adapter that offers `adapter`: all of them, with textures
/// capped at 16384 px like the headless renderer's device.
fn device_limits(adapter: eframe::wgpu::Limits) -> eframe::wgpu::Limits {
    eframe::wgpu::Limits { max_texture_dimension_2d: adapter.max_texture_dimension_2d.min(16384), ..adapter }
}

/// The window couldn't open (no usable graphics adapter or device): say so instead of quitting
/// silently, since release builds on Windows have no console. `gl_next`: the launch guard has
/// the next launch try OpenGL.
fn startup_failed(e: &eframe::Error, gl_next: bool) {
    let next = if gl_next { "The next launch will try OpenGL instead. " } else { "" };
    let message = format!(
        "EffectCraft couldn't start its window: {e}\n\n{next}Updating the graphics driver often helps. If it keeps happening, please report it at https://github.com/storytold/effectcraft/issues with this message."
    );
    log::error!("{message}");
    eprintln!("effectcraft: {message}");
    let _ = rfd::MessageDialog::new()
        .set_level(rfd::MessageLevel::Error)
        .set_title("EffectCraft")
        .set_description(message)
        .set_buttons(rfd::MessageButtons::Ok)
        .show();
}

/// The desktop app: the egui app plus, on macOS, the system menu bar.
struct Desktop {
    app: EffectcraftApp,
    #[cfg(target_os = "macos")]
    menu: native_menu::NativeBar,
    launch: launch_guard::Launch,
    /// The first frame was drawn (logged once).
    drawn: bool,
}

impl eframe::App for Desktop {
    fn logic(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
        #[cfg(target_os = "macos")]
        self.menu.update(&mut self.app, ctx);
        self.app.logic(ctx, frame);
    }

    fn ui(&mut self, ui: &mut egui::Ui, frame: &mut eframe::Frame) {
        self.app.ui(ui, frame);
        if !self.drawn {
            self.drawn = true;
            self.launch.drawn();
            log::info!("first frame drawn");
        }
    }

    fn on_exit(&mut self) {
        self.app.on_exit();
    }

    fn raw_input_hook(&mut self, ctx: &egui::Context, raw_input: &mut egui::RawInput) {
        self.app.raw_input_hook(ctx, raw_input);
    }
}

/// Driven by an agent (`--control`): don't activate the app on launch, so the user's keyboard
/// focus stays where it is (macOS; winit activates ignoring other apps by default).
fn agent_event_loop(agent: bool) -> Option<eframe::EventLoopBuilderHook> {
    #[cfg(target_os = "macos")]
    if agent {
        return Some(Box::new(|b| {
            use winit::platform::macos::EventLoopBuilderExtMacOS;
            b.with_activate_ignoring_other_apps(false);
        }));
    }
    let _ = agent;
    None
}

/// Agents drive the app while its window is covered or on another Space. macOS App Nap would
/// throttle the event loop then, stalling the control channel; opt out for `--control` runs.
fn disable_app_nap() {
    #[cfg(target_os = "macos")]
    {
        use objc2_foundation::{NSActivityOptions, NSProcessInfo, NSString};
        let info = NSProcessInfo::processInfo();
        let reason = NSString::from_str("EffectCraft control channel");
        let opts = NSActivityOptions::UserInitiatedAllowingIdleSystemSleep | NSActivityOptions::LatencyCritical;
        // Leaked on purpose: the activity lasts for the life of the process.
        std::mem::forget(info.beginActivityWithOptions_reason(opts, &reason));
    }
}

#[cfg(test)]
mod tests {
    use super::{Args, parse_args};

    fn parse(args: &[&str]) -> Option<Args> {
        parse_args(args.iter().map(|a| a.to_string()), None)
    }

    /// The window's device never asks for more than the adapter offers (#198).
    #[test]
    fn device_limits_fit_the_adapter() {
        use eframe::wgpu::Limits;
        for adapter in [Limits::downlevel_defaults(), Limits::downlevel_webgl2_defaults(), Limits::default()] {
            let l = super::device_limits(adapter.clone());
            assert!(l.check_limits(&adapter), "{l:?}");
            assert_eq!(l.max_storage_buffers_per_shader_stage, adapter.max_storage_buffers_per_shader_stage);
        }
        let big = Limits { max_texture_dimension_2d: 32768, ..Limits::default() };
        assert_eq!(super::device_limits(big).max_texture_dimension_2d, 16384);
    }

    /// Launching without a project opens an empty project, not the demo (#204).
    #[test]
    fn no_arguments_start_an_empty_project() {
        assert_eq!(parse(&[]), Some(Args::default()));
        assert!(parse(&["--demo"]).is_some_and(|a| a.demo));
        assert!(parse(&["--demo", "--empty"]).is_some_and(|a| !a.demo));
        let a = parse(&["--control", "9877", "--home", "a.ecproj"]).unwrap_or_default();
        assert_eq!((a.control_port, a.home, a.files), (Some(9877), Some(true), vec!["a.ecproj".to_string()]));
        assert_eq!(parse(&["--version"]), None);
        assert_eq!(parse_args(Vec::new(), Some("9000".into())).map(|a| a.control_port), Some(Some(9000)));
    }
}
